
import { Surfer, Tier, Heat } from './types';

export const TOTAL_BUDGET = 70.0;
export const TIER_LIMITS = {
  [Tier.A]: 2,
  [Tier.B]: 4,
  [Tier.C]: 2,
};

export const MOCK_SURFERS: Surfer[] = [
  // Tier A
  { id: 'yago-dora', name: 'Yago Dora', country: 'Brazil', flag: '🇧🇷', stance: 'Goofy', age: 27, value: 11.0, tier: Tier.A, image: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/68cd1329092f16fac35385c3/c97a7e74e_Yago-Dora.png', points: 0, status: 'Waiting' },
  { id: 'ethan-ewing', name: 'Ethan Ewing', country: 'Australia', flag: '🇦🇺', stance: 'Regular', age: 25, value: 10.0, tier: Tier.A, image: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/68cd1329092f16fac35385c3/53aa937f5_Ethan-Ewing.png', points: 0, status: 'Waiting' },
  { id: 'griffin-colapinto', name: 'Griffin Colapinto', country: 'USA', flag: '🇺🇸', stance: 'Regular', age: 25, value: 10.0, tier: Tier.A, image: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/68cd1329092f16fac35385c3/0e6877764_Griffin-Colapinto.png', points: 0, status: 'Waiting' },
  { id: 'jack-robinson', name: 'Jack Robinson', country: 'Australia', flag: '🇦🇺', stance: 'Regular', age: 26, value: 10.0, tier: Tier.A, image: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/68cd1329092f16fac35385c3/4f62274f0_Jack-Robinson.png', points: 0, status: 'Waiting' },
  { id: 'italo-ferreira', name: 'Italo Ferriera', country: 'Brazil', flag: '🇧🇷', stance: 'Goofy', age: 29, value: 9.5, tier: Tier.A, image: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/68cd1329092f16fac35385c3/3ddea78af_Italo-Ferraria.png', points: 0, status: 'Waiting' },
  { id: 'jordy-smith', name: 'Jordy Smith', country: 'South Africa', flag: '🇿🇦', stance: 'Regular', age: 36, value: 9.5, tier: Tier.A, image: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/68cd1329092f16fac35385c3/d589c0194_Jordy-Smith.png', points: 0, status: 'Waiting' },
  { id: 'filipe-toledo', name: 'Filipe Toledo', country: 'Brazil', flag: '🇧🇷', stance: 'Regular', age: 29, value: 9.0, tier: Tier.A, image: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/68cd1329092f16fac35385c3/efc922ebc_Filipe-Toledo.png', points: 0, status: 'Waiting' },
  { id: 'kanoa-igarashi', name: 'Kanoa Igarashi', country: 'Japan', flag: '🇯🇵', stance: 'Regular', age: 26, value: 9.0, tier: Tier.A, image: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/68cd1329092f16fac35385c3/552a8cfc5_kanoa-Igarashi.png', points: 0, status: 'Waiting' },
  { id: 'connor-oleary', name: "Connor O'Leary", country: 'Japan', flag: '🇯🇵', stance: 'Goofy', age: 30, value: 8.0, tier: Tier.A, image: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/68cd1329092f16fac35385c3/8bc34ac4c_Connor-Oleary.png', points: 0, status: 'Waiting' },

  // Tier B
  { id: 'gabriel-medina', name: 'Gabriel Medina', country: 'Brazil', flag: '🇧🇷', stance: 'Goofy', age: 30, value: 8.5, tier: Tier.B, image: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/68cd1329092f16fac35385c3/aebc31dff_Gabby-Medina.png', points: 0, status: 'Waiting' },
  { id: 'barron-mamiya', name: 'Barron Mamiya', country: 'USA', flag: '🇺🇸', stance: 'Regular', age: 24, value: 7.0, tier: Tier.B, image: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/68cd1329092f16fac35385c3/649ca6fb4_Barron-Mamiya.png', points: 0, status: 'Waiting' },
  { id: 'leo-fioravanti', name: 'Leonardo Fioravanti', country: 'Italy', flag: '🇮🇹', stance: 'Regular', age: 26, value: 7.0, tier: Tier.B, image: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/68cd1329092f16fac35385c3/8cf75c02b_Laim-Obrien.png', points: 0, status: 'Waiting' },
  { id: 'joao-chianca', name: 'Joao Chianca', country: 'Brazil', flag: '🇧🇷', stance: 'Regular', age: 23, value: 6.0, tier: Tier.B, image: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/68cd1329092f16fac35385c3/e5a59113a_Jaoa-Chianca.png', points: 0, status: 'Waiting' },
  { id: 'liam-obrien', name: "Liam O'Brien", country: 'Australia', flag: '🇦🇺', stance: 'Regular', age: 25, value: 6.0, tier: Tier.B, image: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/68cd1329092f16fac35385c3/b4e9a0f31_Leo-Fivo.png', points: 0, status: 'Waiting' },
  { id: 'joel-vaughan', name: 'Joel Vaughan', country: 'Australia', flag: '🇦🇺', stance: 'Regular', age: 20, value: 5.5, tier: Tier.B, image: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/68cd1329092f16fac35385c3/fb635d813_Joel-Vaughan.png', points: 0, status: 'Waiting' },
  { id: 'cole-houshmand', name: 'Cole Houshmand', country: 'USA', flag: '🇺🇸', stance: 'Goofy', age: 23, value: 5.0, tier: Tier.B, image: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/68cd1329092f16fac35385c3/466443c69_Cole-Houshmand.png', points: 0, status: 'Waiting' },
  { id: 'jake-marshall', name: 'Jake Marshall', country: 'USA', flag: '🇺🇸', stance: 'Regular', age: 25, value: 5.0, tier: Tier.B, image: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/68cd1329092f16fac35385c3/a9c534c51_Jake-Marshall.png', points: 0, status: 'Waiting' },
  { id: 'crosby-colapinto', name: 'Crosby Colapinto', country: 'USA', flag: '🇺🇸', stance: 'Regular', age: 22, value: 4.5, tier: Tier.B, image: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/68cd1329092f16fac35385c3/3d429d86a_Crosby-Colapinto.png', points: 0, status: 'Waiting' },
  { id: 'matt-mcgillivray', name: 'Matthew McGillivray', country: 'South Africa', flag: '🇿🇦', stance: 'Regular', age: 27, value: 4.5, tier: Tier.B, image: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/68cd1329092f16fac35385c3/71246df27_Matt-Mcgillvary.png', points: 0, status: 'Waiting' },
  { id: 'miguel-pupo', name: 'Miguel Pupo', country: 'Brazil', flag: '🇧🇷', stance: 'Goofy', age: 32, value: 4.5, tier: Tier.B, image: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/68cd1329092f16fac35385c3/316c4ab51_Miggy-Pupo.png', points: 0, status: 'Waiting' },
  { id: 'ryan-callinan', name: 'Ryan Callinan', country: 'Australia', flag: '🇦🇺', stance: 'Goofy', age: 31, value: 4.5, tier: Tier.B, image: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/68cd1329092f16fac35385c3/a76d045f8_Ryan-Callinan.png', points: 0, status: 'Waiting' },
  { id: 'samuel-pupo', name: 'Samuel Pupo', country: 'Brazil', flag: '🇧🇷', stance: 'Regular', age: 23, value: 4.5, tier: Tier.B, image: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/68cd1329092f16fac35385c3/5b1b7ae8f_Sammy-Pupo.png', points: 0, status: 'Waiting' },
  { id: 'imaikalani-devault', name: 'Imaikalani deVault', country: 'USA', flag: '🇺🇸', stance: 'Regular', age: 26, value: 4.0, tier: Tier.B, image: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/68cd1329092f16fac35385c3/90096d2c3_Imaikalani.png', points: 0, status: 'Waiting' },
  { id: 'rio-waida', name: 'Rio Waida', country: 'Indonesia', flag: '🇮🇩', stance: 'Regular', age: 24, value: 4.0, tier: Tier.B, image: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/68cd1329092f16fac35385c3/f65c34ae8_Rio-M.png', points: 0, status: 'Waiting' },
  { id: 'seth-moniz', name: 'Seth Moniz', country: 'USA', flag: '🇺🇸', stance: 'Regular', age: 26, value: 3.5, tier: Tier.B, image: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/68cd1329092f16fac35385c3/5c838d264_Seth-Moniz.png', points: 0, status: 'Waiting' },

  // Tier C
  { id: 'jackson-bunch', name: 'Jackson Bunch', country: 'USA', flag: '🇺🇸', stance: 'Goofy', age: 20, value: 3.0, tier: Tier.C, image: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/68cd1329092f16fac35385c3/31e93a77d_Jackson-Bunch.png', points: 0, status: 'Waiting' },
  { id: 'marco-mignot', name: 'Marco Mignot', country: 'France', flag: '🇫🇷', stance: 'Regular', age: 23, value: 3.0, tier: Tier.C, image: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/68cd1329092f16fac35385c3/af2d4a5a4_Marco-Mignot.png', points: 0, status: 'Waiting' },
  { id: 'alan-cleland', name: 'Alan Cleland', country: 'Mexico', flag: '🇲🇽', stance: 'Regular', age: 21, value: 2.0, tier: Tier.C, image: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/68cd1329092f16fac35385c3/346b79f60_Al-Cleland.png', points: 0, status: 'Waiting' },
  { id: 'ian-gentil', name: 'Ian Gentil', country: 'USA', flag: '🇺🇸', stance: 'Regular', age: 28, value: 2.0, tier: Tier.C, image: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/68cd1329092f16fac35385c3/409612f2e_Ian-Gentil.png', points: 0, status: 'Waiting' },
  { id: 'ramzi-boukhiam', name: 'Ramzi Boukhiam', country: 'Morrocco', flag: '🇲🇦', stance: 'Goofy', age: 30, value: 2.0, tier: Tier.C, image: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/68cd1329092f16fac35385c3/60acda1fa_Ramzi-Boukhaim.png', points: 0, status: 'Waiting' },
  { id: 'george-pittar', name: 'George Pittar', country: 'Australia', flag: '🇦🇺', stance: 'Regular', age: 21, value: 1.5, tier: Tier.C, image: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/68cd1329092f16fac35385c3/5cadaecc4_George-Pittar.png', points: 0, status: 'Waiting' },
  { id: 'alejo-muniz', name: 'Alejo Muniz', country: 'Brazil', flag: '🇧🇷', stance: 'Regular', age: 34, value: 1.0, tier: Tier.C, image: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/68cd1329092f16fac35385c3/fa1a35c18_Alejo-Munoz.png', points: 0, status: 'Waiting' },
  { id: 'deivid-silva', name: 'Deivid Silva', country: 'Brazil', flag: '🇧🇷', stance: 'Goofy', age: 29, value: 1.0, tier: Tier.C, image: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/68cd1329092f16fac35385c3/75c090fdf_Devid-Silva.png', points: 0, status: 'Waiting' },
  { id: 'ian-gouveia', name: 'Ian Gouveia', country: 'Brazil', flag: '🇧🇷', stance: 'Goofy', age: 31, value: 1.0, tier: Tier.C, image: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/68cd1329092f16fac35385c3/85e334aeb_Ian-Gouveia.png', points: 0, status: 'Waiting' },
  { id: 'edgard-groggia', name: 'Edgard Groggia', country: 'Brazil', flag: '🇧🇷', stance: 'Regular', age: 27, value: 0.5, tier: Tier.C, image: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/68cd1329092f16fac35385c3/44eb6a48f_Ed-groggia.png', points: 0, status: 'Waiting' },
];

export const MOCK_HEATS: Heat[] = [
  { id: 'h5', number: 5, time: '10:45 AM', surfers: [{ name: 'F. Toledo', country: 'Brazil', color: 'red' }, { name: 'K. Igarashi', country: 'Japan', color: 'blue' }] },
  { id: 'h6', number: 6, time: '11:20 AM', surfers: [{ name: 'J. Robinson', country: 'Australia', color: 'red' }, { name: 'C. Houshmand', country: 'USA', color: 'blue' }] },
  { id: 'h7', number: 7, time: '11:55 AM', surfers: [{ name: 'J. Florence', country: 'USA', color: 'red' }, { name: 'S. Moniz', country: 'USA', color: 'blue' }] },
  { id: 'h8', number: 8, time: '12:30 PM', surfers: [{ name: 'G. Medina', country: 'Brazil', color: 'red' }, { name: 'C. Colapinto', country: 'USA', color: 'blue' }] },
];
