import { Surfer, Tier, Heat } from './types';

export const TOTAL_BUDGET = 60.0;
export const TIER_LIMITS = {
  [Tier.A]: 3,
  [Tier.B]: 4,
  [Tier.C]: 3,
};

export const MOCK_SURFERS: Surfer[] = [
  // --- TIER A ---
  // Men
  { id: 'yago-dora', name: 'Yago Dora', country: 'Brazil', flag: '🇧🇷', stance: 'Goofy', age: 27, value: 11.0, tier: Tier.A, image: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/68cd1329092f16fac35385c3/c97a7e74e_Yago-Dora.png', points: 0, gender: 'Male', status: 'Waiting' },
  { id: 'ethan-ewing', name: 'Ethan Ewing', country: 'Australia', flag: '🇦🇺', stance: 'Regular', age: 25, value: 10.0, tier: Tier.A, image: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/68cd1329092f16fac35385c3/53aa937f5_Ethan-Ewing.png', points: 0, gender: 'Male', status: 'Waiting' },
  { id: 'jack-robinson', name: 'Jack Robinson', country: 'Australia', flag: '🇦🇺', stance: 'Regular', age: 26, value: 10.0, tier: Tier.A, image: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/68cd1329092f16fac35385c3/4f62274f0_Jack-Robinson.png', points: 0, gender: 'Male', status: 'Waiting' },
  { id: 'connor-oleary', name: "Connor O'Leary", country: 'Japan', flag: '🇯🇵', stance: 'Goofy', age: 30, value: 8.0, tier: Tier.A, image: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/68cd1329092f16fac35385c3/8bc34ac4c_Connor-Oleary.png', points: 0, gender: 'Male', status: 'Waiting' },
  { id: 'barron-mamiya', name: 'Barron Mamiya', country: 'USA', flag: '🇺🇸', stance: 'Regular', age: 24, value: 7.0, tier: Tier.A, image: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/68cd1329092f16fac35385c3/649ca6fb4_Barron-Mamiya.png', points: 0, gender: 'Male', status: 'Waiting' },
  { id: 'cole-houshmand', name: 'Cole Houshmand', country: 'USA', flag: '🇺🇸', stance: 'Goofy', age: 23, value: 5.0, tier: Tier.A, image: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/68cd1329092f16fac35385c3/466443c69_Cole-Houshmand.png', points: 0, gender: 'Male', status: 'Waiting' },
  { id: 'crosby-colapinto', name: 'Crosby Colapinto', country: 'USA', flag: '🇺🇸', stance: 'Regular', age: 22, value: 4.5, tier: Tier.A, image: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/68cd1329092f16fac35385c3/3d429d86a_Crosby-Colapinto.png', points: 0, gender: 'Male', status: 'Waiting' },
  { id: 'alan-cleland', name: 'Alan Cleland', country: 'Mexico', flag: '🇲🇽', stance: 'Regular', age: 22, value: 2.0, tier: Tier.A, image: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/68cd1329092f16fac35385c3/346b79f60_Al-Cleland.png', points: 0, gender: 'Male', status: 'Waiting' },
  { id: 'alejo-muniz', name: 'Alejo Muniz', country: 'Brazil', flag: '🇧🇷', stance: 'Regular', age: 34, value: 1.0, tier: Tier.A, image: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/68cd1329092f16fac35385c3/fa1a35c18_Alejo-Munoz.png', points: 0, gender: 'Male', status: 'Waiting' },
  { id: 'deivid-silva', name: 'Deivid Silva', country: 'Brazil', flag: '🇧🇷', stance: 'Goofy', age: 29, value: 1.0, tier: Tier.A, image: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/68cd1329092f16fac35385c3/75c090fdf_Devid-Silva.png', points: 0, gender: 'Male', status: 'Waiting' },
  { id: 'edgard-groggia', name: 'Edgard Groggia', country: 'Brazil', flag: '🇧🇷', stance: 'Regular', age: 27, value: 0.5, tier: Tier.A, image: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/68cd1329092f16fac35385c3/44eb6a48f_Ed-groggia.png', points: 0, gender: 'Male', status: 'Waiting' },
  // Women
  { id: 'molly-picklum', name: 'Molly Picklum', country: 'Australia', flag: '🇦🇺', stance: 'Regular', age: 21, value: 11.0, tier: Tier.A, image: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/68ce1bb0c05c7a47021428e9/f8218596d_molly-picklum.png', points: 0, gender: 'Female', status: 'Waiting' },
  { id: 'caitlin-simmers', name: 'Caitlin Simmers', country: 'USA', flag: '🇺🇸', stance: 'Regular', age: 18, value: 10.0, tier: Tier.A, image: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/68ce1bb0c05c7a47021428e9/6cf94906a_caitlyn-simmers.png', points: 0, gender: 'Female', status: 'Waiting' },
  { id: 'caroline-marks', name: 'Caroline Marks', country: 'USA', flag: '🇺🇸', stance: 'Goofy', age: 22, value: 9.5, tier: Tier.A, image: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/68ce1bb0c05c7a47021428e9/664d54e46_caroline-marks.png', points: 0, gender: 'Female', status: 'Waiting' },
  { id: 'bettylou-sakura-johnson', name: 'Betty Lou Sakura Johnson', country: 'USA', flag: '🇺🇸', stance: 'Regular', age: 19, value: 8.0, tier: Tier.A, image: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/68ce1bb0c05c7a47021428e9/dfa6b644b_betty-lou-sakura.png', points: 0, gender: 'Female', status: 'Waiting' },

  // --- TIER B ---
  // Men
  { id: 'griffin-colapinto', name: 'Griffin Colapinto', country: 'USA', flag: '🇺🇸', stance: 'Regular', age: 25, value: 10.0, tier: Tier.B, image: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/68cd1329092f16fac35385c3/0e6877764_Griffin-Colapinto.png', points: 0, gender: 'Male', status: 'Waiting' },
  { id: 'italo-ferreira', name: 'Italo Ferriera', country: 'Brazil', flag: '🇧🇷', stance: 'Goofy', age: 29, value: 9.5, tier: Tier.B, image: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/68cd1329092f16fac35385c3/3ddea78af_Italo-Ferraria.png', points: 0, gender: 'Male', status: 'Waiting' },
  { id: 'jordy-smith', name: 'Jordy Smith', country: 'South Africa', flag: '🇿🇦', stance: 'Regular', age: 36, value: 9.5, tier: Tier.B, image: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/68cd1329092f16fac35385c3/d589c0194_Jordy-Smith.png', points: 0, gender: 'Male', status: 'Waiting' },
  { id: 'filipe-toledo', name: 'Filipe Toledo', country: 'Brazil', flag: '🇧🇷', stance: 'Regular', age: 29, value: 9.0, tier: Tier.B, image: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/68cd1329092f16fac35385c3/efc922ebc_Filipe-Toledo.png', points: 0, gender: 'Male', status: 'Waiting' },
  { id: 'kanoa-igarashi', name: 'Kanoa Igarashi', country: 'Japan', flag: '🇯🇵', stance: 'Regular', age: 26, value: 9.0, tier: Tier.B, image: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/68cd1329092f16fac35385c3/552a8cfc5_kanoa-Igarashi.png', points: 0, gender: 'Male', status: 'Waiting' },
  { id: 'gabriel-medina', name: 'Gabriel Medina', country: 'Brazil', flag: '🇧🇷', stance: 'Goofy', age: 30, value: 8.0, tier: Tier.B, image: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/68cd1329092f16fac35385c3/aebc31dff_Gabby-Medina.png', points: 0, gender: 'Male', status: 'Waiting' },
  { id: 'leonardo-fioravanti', name: 'Leonardo Fioravanti', country: 'Italy', flag: '🇮🇹', stance: 'Regular', age: 26, value: 7.0, tier: Tier.B, image: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/68cd1329092f16fac35385c3/b4e9a0f31_Leo-Fivo.png', points: 0, gender: 'Male', status: 'Waiting' },
  { id: 'joao-chianca', name: 'Joao Chianca', country: 'Brazil', flag: '🇧🇷', stance: 'Regular', age: 23, value: 6.0, tier: Tier.B, image: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/68cd1329092f16fac35385c3/e5a59113a_Jaoa-Chianca.png', points: 0, gender: 'Male', status: 'Waiting' },
  { id: 'joel-vaughan', name: 'Joel Vaughan', country: 'Australia', flag: '🇦🇺', stance: 'Regular', age: 20, value: 5.5, tier: Tier.B, image: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/68cd1329092f16fac35385c3/fb635d813_Joel-Vaughan.png', points: 0, gender: 'Male', status: 'Waiting' },
  { id: 'jake-marshall', name: 'Jake Marshall', country: 'USA', flag: '🇺🇸', stance: 'Regular', age: 25, value: 5.0, tier: Tier.B, image: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/68cd1329092f16fac35385c3/a9c534c51_Jake-Marshall.png', points: 0, gender: 'Male', status: 'Waiting' },
  { id: 'imaikalani-devault', name: 'Imaikalani deVault', country: 'USA', flag: '🇺🇸', stance: 'Regular', age: 26, value: 4.0, tier: Tier.B, image: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/68cd1329092f16fac35385c3/90096d2c3_Imaikalani.png', points: 0, gender: 'Male', status: 'Waiting' },
  { id: 'jackson-bunch', name: 'Jackson Bunch', country: 'USA', flag: '🇺🇸', stance: 'Goofy', age: 20, value: 3.0, tier: Tier.B, image: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/68cd1329092f16fac35385c3/31e93a77d_Jackson-Bunch.png', points: 0, gender: 'Male', status: 'Waiting' },
  { id: 'ian-gentil', name: 'Ian Gentil', country: 'USA', flag: '🇺🇸', stance: 'Regular', age: 28, value: 2.0, tier: Tier.B, image: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/68cd1329092f16fac35385c3/409612f2e_Ian-Gentil.png', points: 0, gender: 'Male', status: 'Waiting' },
  { id: 'george-pittar', name: 'George Pittar', country: 'Australia', flag: '🇦🇺', stance: 'Regular', age: 21, value: 1.5, tier: Tier.B, image: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/68cd1329092f16fac35385c3/5cadaecc4_George-Pittar.png', points: 0, gender: 'Male', status: 'Waiting' },
  { id: 'ian-gouveia', name: 'Ian Gouveia', country: 'Brazil', flag: '🇧🇷', stance: 'Goofy', age: 31, value: 1.0, tier: Tier.B, image: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/68cd1329092f16fac35385c3/85e334aeb_Ian-Gouveia.png', points: 0, gender: 'Male', status: 'Waiting' },
  // Women
  { id: 'erin-brooks', name: 'Erin Brooks', country: 'Canada', flag: '🇨🇦', stance: 'Goofy', age: 16, value: 7.0, tier: Tier.B, image: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/68ce1bb0c05c7a47021428e9/5e0fc50ec_erin-brooks.png', points: 0, gender: 'Female', status: 'Waiting' },
  { id: 'gabriela-bryan', name: 'Gabriela Bryan', country: 'USA', flag: '🇺🇸', stance: 'Regular', age: 22, value: 6.5, tier: Tier.B, image: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/68ce1bb0c05c7a47021428e9/c3a3ce643_gabby-bryant.png', points: 0, gender: 'Female', status: 'Waiting' },
  { id: 'tyler-wright', name: 'Tyler Wright', country: 'Australia', flag: '🇦🇺', stance: 'Regular', age: 29, value: 6.5, tier: Tier.B, image: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/68ce1bb0c05c7a47021428e9/abf499dea_tyler-wright.png', points: 0, gender: 'Female', status: 'Waiting' },
  { id: 'lakey-peterson', name: 'Lakey Peterson', country: 'USA', flag: '🇺🇸', stance: 'Regular', age: 29, value: 5.0, tier: Tier.B, image: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/68ce1bb0c05c7a47021428e9/bad52d00a_lakey-peterson.png', points: 0, gender: 'Female', status: 'Waiting' },
  { id: 'brisa-hennessy', name: 'Brisa Hennessy', country: 'Costa Rica', flag: '🇨🇷', stance: 'Regular', age: 24, value: 5.0, tier: Tier.B, image: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/68ce1bb0c05c7a47021428e9/18462750c_brisa-hennessy.png', points: 0, gender: 'Female', status: 'Waiting' },
  { id: 'luana-silva', name: 'Luana Silva', country: 'Brazil', flag: '🇧🇷', stance: 'Regular', age: 19, value: 4.5, tier: Tier.B, image: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/68ce1bb0c05c7a47021428e9/b91cac22b_luana-silva.png', points: 0, gender: 'Female', status: 'Waiting' },
  { id: 'sally-fitzgibbons', name: 'Sally Fitzgibbons', country: 'Australia', flag: '🇦🇺', stance: 'Regular', age: 33, value: 4.5, tier: Tier.B, image: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/68ce1bb0c05c7a47021428e9/52b4ebf42_sally-fitzgibbons.png', points: 0, gender: 'Female', status: 'Waiting' },
  { id: 'isabella-nichols', name: 'Isabella Nichols', country: 'Australia', flag: '🇦🇺', stance: 'Regular', age: 21, value: 4.0, tier: Tier.B, image: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/68ce1bb0c05c7a47021428e9/88b56d5e2_isabella-nichols.png', points: 0, gender: 'Female', status: 'Waiting' },
  { id: 'sawyer-lindblad', name: 'Sawyer Lindblad', country: 'USA', flag: '🇺🇸', stance: 'Goofy', age: 18, value: 4.0, tier: Tier.B, image: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/68ce1bb0c05c7a47021428e9/f29351216_sawyer-linblad.png', points: 0, gender: 'Female', status: 'Waiting' },

  // --- TIER C ---
  // Men
  { id: 'liam-obrien', name: "Liam O'Brien", country: 'Australia', flag: '🇦🇺', stance: 'Regular', age: 25, value: 6.0, tier: Tier.C, image: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/68cd1329092f16fac35385c3/8cf75c02b_Laim-Obrien.png', points: 0, gender: 'Male', status: 'Waiting' },
  { id: 'matt-mcgillivray', name: 'Matthew McGillivray', country: 'South Africa', flag: '🇿🇦', stance: 'Regular', age: 27, value: 4.5, tier: Tier.C, image: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/68cd1329092f16fac35385c3/71246df27_Matt-Mcgillvary.png', points: 0, gender: 'Male', status: 'Waiting' },
  { id: 'miguel-pupo', name: 'Miguel Pupo', country: 'Brazil', flag: '🇧🇷', stance: 'Goofy', age: 32, value: 4.5, tier: Tier.C, image: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/68cd1329092f16fac35385c3/316c4ab51_Miggy-Pupo.png', points: 0, gender: 'Male', status: 'Waiting' },
  { id: 'ryan-callinan', name: 'Ryan Callinan', country: 'Australia', flag: '🇦🇺', stance: 'Goofy', age: 31, value: 4.5, tier: Tier.C, image: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/68cd1329092f16fac35385c3/a76d045f8_Ryan-Callinan.png', points: 0, gender: 'Male', status: 'Waiting' },
  { id: 'samuel-pupo', name: 'Samuel Pupo', country: 'Brazil', flag: '🇧🇷', stance: 'Regular', age: 23, value: 4.5, tier: Tier.C, image: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/68cd1329092f16fac35385c3/5b1b7ae8f_Sammy-Pupo.png', points: 0, gender: 'Male', status: 'Waiting' },
  { id: 'rio-waida', name: 'Rio Waida', country: 'Indonesia', flag: '🇮🇩', stance: 'Regular', age: 24, value: 4.0, tier: Tier.C, image: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/68cd1329092f16fac35385c3/f65c34ae8_Rio-M.png', points: 0, gender: 'Male', status: 'Waiting' },
  { id: 'seth-moniz', name: 'Seth Moniz', country: 'USA', flag: '🇺🇸', stance: 'Regular', age: 26, value: 3.5, tier: Tier.C, image: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/68cd1329092f16fac35385c3/5c838d264_Seth-Moniz.png', points: 0, gender: 'Male', status: 'Waiting' },
  { id: 'marco-mignot', name: 'Marco Mignot', country: 'France', flag: '🇫🇷', stance: 'Regular', age: 23, value: 3.0, tier: Tier.C, image: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/68cd1329092f16fac35385c3/af2d4a5a4_Marco-Mignot.png', points: 0, gender: 'Male', status: 'Waiting' },
  { id: 'ramzi-boukhiam', name: 'Ramzi Boukhiam', country: 'Morrocco', flag: '🇲🇦', stance: 'Goofy', age: 30, value: 2.0, tier: Tier.C, image: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/68cd1329092f16fac35385c3/60acda1fa_Ramzi-Boukhaim.png', points: 0, gender: 'Male', status: 'Waiting' },
  // Women
  { id: 'johanne-defay', name: 'Johanne Defay', country: 'France', flag: '🇫🇷', stance: 'Regular', age: 30, value: 1.5, tier: Tier.C, image: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/68ce1bb0c05c7a47021428e9/94b9eedd2_johanne-defay.png', points: 0, gender: 'Female', status: 'Waiting' },
  { id: 'tatiana-weston-webb', name: 'Tatiana Weston-Webb', country: 'Brazil', flag: '🇧🇷', stance: 'Goofy', age: 27, value: 1.5, tier: Tier.C, image: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/68ce1bb0c05c7a47021428e9/6c42e2917_tatiana-weston-webb.png', points: 0, gender: 'Female', status: 'Waiting' },
  { id: 'вахine-fierro', name: 'Vahine Fierro', country: 'France', flag: '🇫🇷', stance: 'Goofy', age: 24, value: 1.0, tier: Tier.C, image: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/68ce1bb0c05c7a47021428e9/7e2031507_vahine-fierro.png', points: 0, gender: 'Female', status: 'Waiting' },
  { id: 'bella-kenworthy', name: 'Bella Kenworthy', country: 'USA', flag: '🇺🇸', stance: 'Regular', age: 17, value: 2.0, tier: Tier.C, image: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/68ce1bb0c05c7a47021428e9/326cc8f41_bella-kenworthy.png', points: 0, gender: 'Female', status: 'Waiting' },
  { id: 'nadia-erostarbe', name: 'Nadia Erostarbe', country: 'Basuqe', flag: '🇪🇸', stance: 'Goofy', age: 23, value: 0.5, tier: Tier.C, image: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/68ce1bb0c05c7a47021428e9/3e8090198_nadia-erostarbe.png', points: 0, gender: 'Female', status: 'Waiting' },
];

export const MOCK_HEATS: Heat[] = [
  { id: 'h5', number: 5, time: '10:45 AM', surfers: [{ name: 'F. Toledo', country: 'Brazil', color: 'red' }, { name: 'K. Igarashi', country: 'Japan', color: 'blue' }] },
  { id: 'h6', number: 6, time: '11:20 AM', surfers: [{ name: 'J. Robinson', country: 'Australia', color: 'red' }, { name: 'C. Houshmand', country: 'USA', color: 'blue' }] },
  { id: 'h7', number: 7, time: '11:55 AM', surfers: [{ name: 'J. Florence', country: 'USA', color: 'red' }, { name: 'S. Moniz', country: 'USA', color: 'blue' }] },
  { id: 'h8', number: 8, time: '12:30 PM', surfers: [{ name: 'G. Medina', country: 'Brazil', color: 'red' }, { name: 'C. Colapinto', country: 'USA', color: 'blue' }] },
];
