import { createClient } from '@supabase/supabase-js';
import * as dotenv from 'dotenv';
dotenv.config({ path: '.env.local' });

const supabaseUrl = process.env.VITE_SUPABASE_URL;
const supabaseKey = process.env.VITE_SUPABASE_ANON_KEY;
const supabase = createClient(supabaseUrl, supabaseKey);

const tiersData = [
    { name: "Samuel Pupo", tier: "A" },
    { name: "Bronson Meydi", tier: "A" },
    { name: "Jorgann Couzinet", tier: "A" },
    { name: "Winter Vincent", tier: "A" },
    { name: "Imaikalani deVault", tier: "A" },
    { name: "Luke Thompson", tier: "A" },
    { name: "Mateus Herdy", tier: "A" },
    { name: "Liam O'Brien", tier: "A" },
    { name: "Jordan Lawler", tier: "A" },
    { name: "Eli Hanneman", tier: "A" },
    { name: "Ian Gentil", tier: "A" },
    { name: "Kauli Vaast", tier: "A" },
    { name: "Ryan Callinan", tier: "A" },
    { name: "Levi Slawson", tier: "A" },
    { name: "Morgan Cibilic", tier: "A" },
    { name: "Jacob Willcox", tier: "A" },
    { name: "Oscar Berry", tier: "A" },
    { name: "Callum Robson", tier: "A" },
    { name: "Jackson Bunch", tier: "A" },
    { name: "Dimitri Poulos", tier: "A" },
    { name: "George Pittar", tier: "A" },
    { name: "Shohei Kato", tier: "B" },
    { name: "Hiroto Ohhara", tier: "B" },
    { name: "Ryan Huckabee", tier: "B" },
    { name: "Michael Rodrigues", tier: "B" },
    { name: "Lucca Mesinas", tier: "B" },
    { name: "Carlos Munoz", tier: "B" },
    { name: "Adur Amatriain", tier: "B" },
    { name: "Edgard Groggia", tier: "B" },
    { name: "Nolan Rapoza", tier: "B" },
    { name: "Finn McGill", tier: "B" },
    { name: "Xavier Huxtable", tier: "B" },
    { name: "Oliver Zietz", tier: "B" },
    { name: "Riaru Ito", tier: "B" },
    { name: "Kyuss King", tier: "B" },
    { name: "Kade Matson", tier: "B" },
    { name: "Billy Stairmand", tier: "B" },
    { name: "Lucas Vicente", tier: "B" },
    { name: "Franco Radziunas", tier: "B" },
    { name: "Shion Crawford", tier: "B" },
    { name: "Keoni Lasa", tier: "B" },
    { name: "Mikey McDonagh", tier: "B" },
    { name: "Charly Quivront", tier: "B" },
    { name: "Keijiro Nishi", tier: "B" },
    { name: "Taro Watanabe", tier: "B" },
    { name: "Lucas Cassity", tier: "B" },
    { name: "Lucas Silveira", tier: "B" },
    { name: "Jackson Baker", tier: "B" },
    { name: "Igor Moraes", tier: "C" },
    { name: "Dakoda Walters", tier: "C" },
    { name: "Mihimana Braye", tier: "C" },
    { name: "Dom Thomas", tier: "C" },
    { name: "Luke Swanson", tier: "C" },
    { name: "Tenshi Iwami", tier: "C" },
    { name: "Lennix Smith", tier: "C" },
    { name: "Caleb Tancred", tier: "C" },
    { name: "Dylan Moffat", tier: "C" },
    { name: "Daiki Tanaka", tier: "C" },
    { name: "Rylan Beavers", tier: "C" },
    { name: "Eden Hasson", tier: "C" },
    { name: "Maxime Huscenot", tier: "C" },
    { name: "Alister Reginato", tier: "C" },
    { name: "Taj Stokes", tier: "C" },
    { name: "Willem Watson", tier: "C" },
    { name: "Jarvis Earle", tier: "C" },
    { name: "Julian Wilson", tier: "C" },
    { name: "Makana Franzmann", tier: "C" },
    { name: "Ocean Lancaster", tier: "C" },
    { name: "Joh Azuchi", tier: "C" },
    { name: "Rafael Teixeira", tier: "C" },
    { name: "Reef Heazlewood", tier: "C" },
    { name: "Harley Walters", tier: "C" },
    { name: "Luke Tema", tier: "C" },
    { name: "Jose Francisco", tier: "C" },
    { name: "Slade Prestwich", tier: "C" },
    { name: "Oliver Ryssenbeek", tier: "C" },
    { name: "Justin Becret", tier: "C" },
    { name: "Tully Wylie", tier: "C" },
    { name: "Hayden Rodgers", tier: "C" },
    { name: "Ben Lorentson", tier: "C" }
];

const queries = tiersData.map(({ name, tier }) => `UPDATE surfers SET tier = '${tier}' WHERE name ILIKE '%${name.replace(/'/g, "''")}%';`).join('\n');

import fs from 'fs';
fs.writeFileSync('sync-tiers.sql', queries);
console.log('SQL generated. Run with: PGPASSWORD=postgres psql -h 127.0.0.1 -p 54322 -U postgres -d postgres -f sync-tiers.sql');
