CREATE TABLE IF NOT EXISTS public.surfers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  name TEXT NOT NULL,
  country TEXT,
  flag TEXT,
  stance TEXT,
  age INTEGER,
  value NUMERIC,
  tier TEXT,
  image TEXT
);

ALTER TABLE public.surfers ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users" ON public.surfers
  FOR SELECT USING (true);
